[FIX#100805] [Piscine] Correction mode php + ajout variable login
etna-alternance/std_comment pull request #3
Opened 2019-04-26 13:43 UTC by Agraael

Correction de la detection du mode PHP et de tout les autres mnodes avec extension.
Ajout d'un variable header-etna-login pour définir uin login par défault

2019-04-30 09:07 UTC, Timer91 requested changes

2019-04-30 09:07 UTC, Timer91 commented on std_comment.el
> +(defvar std-sscript-alist     '( (cs . "#!/bin/sh")  (cc . "## ") (ce . "##")))
Nope, laisse la ligne telle qu’elle etait. C’est le shebang officiel pour Bash

2019-04-30 09:07 UTC, Timer91 commented on std_comment.el
> +(defvar std-php-alist         '( (cs . "#!/usr/local/bin/php\n<?php") (cc . "// ")(ce . "//")))
Le shebang va varier en fonction des versions, je serai donc d’avis qu’on ne le mette pas dans le header. Tu peux donc laisser les /b

2019-06-07 15:16 UTC, Barbatrou approved these changes

2019-06-07 15:51 UTC, merged